-- 修复通知表类型枚举，添加 GUESTBOOK 类型
ALTER TABLE t_notification
MODIFY COLUMN type ENUM('COMMENT', 'REPLY', 'LIKE', 'AT_MENTION', 'MESSAGE_BOARD', 'GUESTBOOK', 'PRIVATE_MESSAGE', 'FOLLOW', 'SYSTEM') NOT NULL COMMENT '通知类型';
